language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install numpy nose coverage pep8
  - pip install .
script:
  - nosetests --with-coverage --cover-package torchfile
  - pep8 torchfile.py
after_success: coveralls
